helm:
  parameters:
  - name: changedetection-io.image.repository
    value: ghcr.io/dgtlmoon/changedetection.io
    forcestring: true
  - name: changedetection-io.image.tag
    value: 0.45.14
    forcestring: true
