---
apiVersion: v2
description: Mealie is a self hosted recipe manager and meal planner.
name: mealie
version: "1.5.1"
keywords:
  - mealie
sources:
  - https://github.com/bjw-s/helm-charts
  - https://github.com/mealie-recipes/mealie/
dependencies:
  - name: app-template
    repository: "@bjws"
    version: "3.1.0"
    alias: mealie