helm:
  parameters:
  - name: prometheus.prometheus.image.image.repository
    value: quay.io/prometheus/prometheus
    forcestring: true
  - name: prometheus.prometheus.image.image.tag
    value: v2.48.1
    forcestring: true
  - name: prometheus-adapter.image.repository
    value: registry.k8s.io/prometheus-adapter/prometheus-adapter
    forcestring: true
  - name: prometheus-adapter.image.tag
    value: v0.11.2
    forcestring: true
