prometheus:
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  nodeExporter:
    enabled: true
    hostNetwork: true
    hostPID: true
    hostRootfs: true
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: NoSchedule
    resources:
      limits:
        cpu: 150m
        memory: 75Mi
      requests:
        cpu: 25m
        memory: 30Mi
  server:
    baseURL: "http://prom.xtr.pub"
    global:
      scrape_interval: 1m
      scrape_timeout: 10s
      evaluation_interval: 1m
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        ingress.kubernetes.io/protocol: http
        cert-manager.io/cluster-issuer: le-prod
      hosts:
        - prom.xtr.pub
      tls:
        - hosts:
          - prom.xtr.pub
          secretName: tls-secret 
    persistentVolume:
      size: 7Gi
    statefulSet:
      enabled: true
      headless:
        gRPC:
          enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 4500Mi
      requests:
        cpu: 100m
        memory: 2Gi
    service:
      gRPC:
        enabled: true
    retention: "1d"
  networkPolicy:
    enabled: true

prometheus-adapter:
  prometheus:
    url: http://prometheus-server
    port: 80
  resources: 
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 2500m
      memory: 2500Mi