---
apiVersion: v2
description: A simple, powerful publishing platform that allows you to share your stories with the world
name: openwebui
version: "1.0.0"
keywords:
  - openwebui
sources:
  - https://github.com/bjw-s/helm-charts
  - https://github.com/open-webui/open-webui
  - https://docs.openwebui.com/
dependencies:
  - name: app-template
    repository: "@bjws"
    version: "3.1.0"
    alias: openwebui