apiVersion: v1
kind: ConfigMap
metadata:
  name: default-controller-env
  namespace: {{ .Release.Namespace }}
data:
  {{- with .Values.configMap.controllerEnv }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}