kured:
  deploy: false
  revisionHistoryLimit: 3
  dsAnnotations:
    secrets.infisical.com/auto-reload: "true"
  extraEnvVars:
  - name: KURED_SLACK_CHANNEL
    valueFrom:
      secretKeyRef:
        name: config-vars
        key: KURED_SLACK_CHANNEL
  - name: KURED_NOTIFY_URL
    valueFrom:
      secretKeyRef:
        name: config-vars
        key: KURED_NOTIFY_URL
  configuration:
    timeZone: "America/New_York"
    startTime: "02:00"
    endTime: "06:00"
    period: "30m0s"
    drainGracePeriod: "45"
    drainTimeout: "20m"
    rebootDelay: "30s"
    forceReboot: true
    annotateNodes: "true"
    messageTemplateDrain: "Draining node %s"
    messageTemplateReboot: "Rebooting node %s"
    messageTemplateUncordon: "Node %s rebooted & uncordoned successfully! It is back in action!"

# infisicalSecret:
#   config-vars:
#     syncInterval: 900