helm:
  parameters:
  - name: sabnzbd.image.repository
    value: quay.io/linuxserver.io/sabnzbd
    forcestring: true
  - name: sabnzbd.image.tag
    value: 4.2.1
    forcestring: true
  - name: radarr.image.repository
    value: quay.io/linuxserver.io/radarr
    forcestring: true
  - name: radarr.image.tag
    value: 5.2.6
    forcestring: true
