helm:
  parameters:
  - name: sabnzbd.controllers.sabnzbd.containers.main.image.repository
    value: ghcr.io/linuxserver/sabnzbd
    forcestring: true
  - name: sabnzbd.controllers.sabnzbd.containers.main.image.tag
    value: 4.3.3
    forcestring: true
  - name: sonarr.controllers.sonarr.containers.main.image.repository
    value: ghcr.io/linuxserver/sonarr
    forcestring: true
  - name: sonarr.controllers.sonarr.containers.main.image.tag
    value: 4.0.9
    forcestring: true
