helm:
  parameters:
  - name: sabnzbd.controllers.sabnzbd.containers.main.image.repository
    value: quay.io/linuxserver.io/sabnzbd
    forcestring: true
  - name: sabnzbd.controllers.sabnzbd.containers.main.image.tag
    value: 4.3.1
    forcestring: true
  - name: radarr.controllers.main.containers.main.image.repository
    value: quay.io/linuxserver.io/radarr
    forcestring: true
  - name: radarr.controllers.main.containers.main.image.tag
    value: "5.14"
    forcestring: true
  - name: sonarr.controllers.sonarr.containers.main.image.repository
    value: quay.io/linuxserver.io/sonarr
    forcestring: true
  - name: sonarr.image.tag
    value: 4.0.4
    forcestring: true
