helm:
  parameters:
  - name: sabnzbd.image.repository
    value: quay.io/linuxserver.io/sabnzbd
    forcestring: true
  - name: sabnzbd.image.tag
    value: latest@sha256:4b654fcb49a6301305dc8db42ef119734ed35fd2ef1d3b9144cce90f0cc64a09
    forcestring: true
  - name: sonarr.image.repository
    value: quay.io/linuxserver.io/sonarr
    forcestring: true
  - name: sonarr.image.tag
    value: latest@sha256:b1eeafb10a3eaa151694e3dd893c136d745c5d61ebbe9c731e65ca336a39a117
    forcestring: true
  - name: radarr.image.repository
    value: quay.io/linuxserver.io/radarr
    forcestring: true
  - name: radarr.image.tag
    value: latest@sha256:89168fef2fba0704da8803a466e3668a92b119a544db5c5e2dba88723d41e240
    forcestring: true
