helm:
  parameters:
  - name: sabnzbd.image.repository
    value: quay.io/linuxserver.io/sabnzbd
    forcestring: true
  - name: sabnzbd.image.tag
    value: 4.2.0
    forcestring: true
  - name: image.name
    value: quay.io/linuxserver.io/sonarr
    forcestring: true
  - name: image.tag
    value: v4
    forcestring: true
  - name: radarr.image.repository
    value: quay.io/linuxserver.io/radarr
    forcestring: true
  - name: radarr.image.tag
    value: "5.14"
    forcestring: true
