helm:
  parameters:
  - name: sabnzbd.image.repository
    value: quay.io/linuxserver.io/sabnzbd
    forcestring: true
  - name: sabnzbd.image.tag
    value: latest@sha256:545c82833c1ac1c265a29188d0411c5840db6534297a3efe785d7f0cf723bf75
    forcestring: true
  - name: sonarr.image.repository
    value: quay.io/linuxserver.io/sonarr
    forcestring: true
  - name: sonarr.image.tag
    value: latest@sha256:4f69472a0cdea29e23967db6a3395487539b759def3920327d1f49ae00b9dfd4
    forcestring: true
  - name: radarr.image.repository
    value: quay.io/linuxserver.io/radarr
    forcestring: true
  - name: radarr.image.tag
    value: latest@sha256:b4ea6d2132710253d14b2543a3acf6ad63c3feca9afd39e7de806592ec1ef466
    forcestring: true
