helm:
  parameters:
  - name: sabnzbd.image.repository
    value: quay.io/linuxserver.io/sabnzbd
    forcestring: true
  - name: sabnzbd.image.tag
    value: latest@sha256:6ada61ea4f3bfd7bd25ef787e0269af690277c010d3e1c70d0d00a517aa8a220
    forcestring: true
  - name: sonarr.image.repository
    value: quay.io/linuxserver.io/sonarr
    forcestring: true
  - name: sonarr.image.tag
    value: latest@sha256:8ddef33cb4684881c34da8be2ba46ed0fb7d9f4bd1725cba7bf3c99ea6f03a7c
    forcestring: true
  - name: radarr.image.repository
    value: quay.io/linuxserver.io/radarr
    forcestring: true
  - name: radarr.image.tag
    value: latest@sha256:b4ea6d2132710253d14b2543a3acf6ad63c3feca9afd39e7de806592ec1ef466
    forcestring: true
