helm:
  parameters:
  - name: radarr.controllers.radarr.containers.main.image.repository
    value: ghcr.io/linuxserver/radarr
    forcestring: true
  - name: radarr.controllers.radarr.containers.main.image.tag
    value: 5.6.0
    forcestring: true
  - name: sonarr.controllers.sonarr.containers.main.image.repository
    value: ghcr.io/linuxserver/sonarr
    forcestring: true
  - name: sonarr.controllers.sonarr.containers.main.image.tag
    value: 4.0.6
    forcestring: true
