sabnzbd:
  global:
    fullnameOverride: sabnzbd
  defaultPodOptions:
    automountServiceAccountToken: false
    labels:
      application: sabnzbd
    securityContext:
      seccompProfile:
        type: RuntimeDefault
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 50
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - plex
            namespaces:
            - plex
            topologyKey: kubernetes.io/hostname
  initContainers:
    copy-config:  
      name: copy-config
      image: quay.io/prometheus/busybox:latest
      command: ["sh", "-c", "cp /cm/config.xml /config/config.xml && chown 911:911  /config/config.xml"] 
      volumeMounts:
      - name: config
        mountPath: /config
      - name: cm-config
        mountPath: /cm
  controllers:
    main:
      annotations:
        secrets.infisical.com/auto-reload: "true"
      containers:
        main:
          type: deployment
          image:
            repository: quay.io/linuxserver.io/sabnzbd
            tag: "4.2.3"
            pullPolicy: IfNotPresent
          env:
            TZ: "America/New_York"
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
          resources:
            limits:
              cpu: "8"
              memory: 3500Mi
            requests:
              cpu: 125m
              memory: 128Mi
  service:
    main:
      extraSelectorLabels:
        application: sabnzbd
      ports:
        http:
          enabled: true
          port: 8080
          primary: true
          protocol: HTTP
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
      hosts:
        - host: mediadepot.xtr.pub
          paths:
            - path: /sabnzbd
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
      - hosts:
        - mediadepot.xtr.pub
        secretName: tls-secret
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 128Mi
      storageClass: ec-silver
      globalMounts:
        - path: /config
    incomplete-downloads:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteMany
      size: 150Gi
      storageClass: fs-silver
      globalMounts:
        - path: /incomplete-downloads
    downloads:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteMany
      size: 200Gi
      storageClass: fs-silver
      globalMounts:
        - path: /downloads
    cm-config:
      enabled: true
      type: custom
      volumeSpec:
        secret:
          secretName: sabnzbd-config
      globalMounts:
        - path: /cm

  networkpolicies:
    main:
      enabled: true
      controller: main
      podSelector:
        matchLabels:
          application: ghost
      policyTypes:
        - Ingress
        - Egress
      rules:
        ingress:
          - from:
              - podSelector:
                  matchLabels:
                    app.kubernetes.io/instance: mediadepot
          - from:
              - namespaceSelector:
                  matchLabels:
                    name: traefik
                podSelector:
                  matchLabels:
                     app.kubernetes.io/name: traefik
        egress:
          - to:
              - namespaceSelector: {}
                podSelector:
                  matchLabels:
                    k8s-app: kube-dns
            ports:
              - port: 53
                protocol: UDP
          - to:
              - podSelector:
                  matchLabels:
                    app.kubernetes.io/instance: mediadepot

infisicalSecret:
  sabnzbd-config:
    syncInterval: 120
