nfd:
  enabled: true

labeller:
  enabled: true

namespace: kube-system

dp:
  image:
    repository: docker.io/rocm/k8s-device-plugin
    tag: "1.25.2.5"
  resources:
    requests:
      cpu: 10m
      memory: 8Mi
    limits:
      cpu: 25m
      memory: 24Mi

lbl:
  image:
    repository: docker.io/rocm/k8s-device-plugin
    tag: "labeller-1.25.2.5"
  resources:
    requests:
      cpu: 10m
      memory: 16Mi
    limits:
      cpu: 125m
      memory: 24Mi

imagePullSecrets: []

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists

node_selector:
  feature.node.kubernetes.io/pci-0300_1002.present: "true"
  kubernetes.io/arch: amd64