apiVersion: v2
name: trivy-operator
description: Keeps security report resources updated
type: application
version: 0.24.1
keywords:
  - aquasecurity
  - trivyoperator
  - trivy
home: https://github.com/aquasecurity/trivy-operator
dependencies:
  - name: trivy-operator
    version: "0.24.1"
    repository: '@aqua'
    condition: trivy-operator.deploy