llama:
  defaultPodOptions:
    automountServiceAccountToken: false
    dnsConfig:
      options:
        - name: ndots
          value: "3"
    securityContext:
      # runAsUser: 1234
      # fsGroup: 1234
      # fsGroupChangePolicy: "Always"
      # runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - "intortus"
  controllers:
    llama:
      type: deployment
      initContainers:
        model-init:
          image:
            repository: "quay.io/prometheus/busybox"
            tag: "latest"
            pullPolicy: IfNotPresent
          command: ["sh", "-c", "chown 1234:1234 /app/models -Rf && ls -lsatr /app/models/"]
          # command: ["sh", "-c", "wget --no-clobber -P /app/models https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/resolve/main/Phi-3-mini-4k-instruct-fp16.gguf && chown 1234:1234 /app/modesl/ -Rf && ls -al /app/models/"]
      containers:
        main:
          image:
            repository: erkerb4/llama.cpp-server
            tag: "6.1.1-1"
            pullPolicy: IfNotPresent
          args: ["--host", "0.0.0.0","-hfr","xtuner/llava-phi-3-mini-gguf","-hff","llava-phi-3-mini-f16.gguf","-n","512", "-ngl","99", "-c", "4096", "-t", "8","--timeout", "900", "--log-disable", "--mlock"]
          env:
            TZ: "America/New_York"
            HSA_OVERRIDE_GFX_VERSION: "9.0.0"
            HCC_AMDGPU_TARGET: "gfx900"
          probes:
            startup:
              enabled: true
              custom: true
              type: HTTP
              spec:
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 150
                periodSeconds: 10
                timeoutSeconds: 3
                failureThreshold: 3
            readiness:
              enabled: true
              custom: true
              type: HTTP
              spec:
                httpGet:
                  path: /health
                  scheme: HTTP
                  port: 8080
                periodSeconds: 10
                timeoutSeconds: 3
                failureThreshold: 3
            liveness:
              enabled: true
              custom: true
              type: HTTP
              spec:
                httpGet:
                  path: /health
                  scheme: HTTP
                  port: 8080
                periodSeconds: 10
                timeoutSeconds: 3
                failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          resources:
            limits:
              cpu: "8"
              memory: 12Gi
              amd.com/gpu: 1
            requests:
              cpu: "1"
              memory: 2Gi
              amd.com/gpu: 1

    webui:
      type: deployment
      containers:
        main:
          image:
            repository: ghcr.io/open-webui/open-webui
            tag: "main"
            pullPolicy: IfNotPresent
          env:
            TZ: "America/New_York"
            OPENAI_API_BASE_URL: "http://llama:8080/v1"
            OPENAI_API_KEYS: "none"
            WEBUI_AUTH: "false"
            WEBUI_URL: "https://llama.xtr.pub"
            ENABLE_LITELLM: "false"
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "150m"
              memory: 256Mi

  service:
    llama:
      controller: llama
      annotations:
        traefik.ingress.kubernetes.io/service.serversscheme: http
      ports:
        http:
          enabled: true
          primary: true
          port: 8080
          protocol: HTTP
    webui:
      controller: webui
      annotations:
        traefik.ingress.kubernetes.io/service.serversscheme: http
      ports:
        http:
          enabled: true
          primary: true
          port: 8080
          protocol: HTTP

  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
      hosts:
        - host: llama.xtr.pub
          paths:
            - path: /
              pathType: ImplementationSpecific
              service:
                identifier: webui
                port: http
      tls:
      - hosts:
        - llama.xtr.pub
        secretName: tls-secret

  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      storageClass: ec-silver-r1
      accessMode: ReadWriteOnce
      size: "30Gi"
      advancedMounts:
        llama:
          main:
            - path: /app/models
          model-init:
            - path: /app/models
    web:
      enabled: true
      type: persistentVolumeClaim
      storageClass: ec-gold
      accessMode: ReadWriteOnce
      size: "1Gi"
      advancedMounts:
        webui:
          main:
            - path: /app/backend/data

  networkpolicies:
    main:
      enabled: false
      controller: llama
      policyTypes:
        - Ingress
        - Egress
      rules:
        ingress:
          - from:
              - namespaceSelector:
                  matchLabels:
                    name: traefik
                podSelector:
                  matchLabels:
                     app.kubernetes.io/name: traefik
          - from:
              - podSelector: {}
        egress:
          - to:
              - namespaceSelector: {}
                podSelector:
                  matchLabels:
                    k8s-app: kube-dns
            ports:
              - port: 53
                protocol: UDP
          - to:
              - podSelector: {}
          - to:
              - ipBlock:
                  cidr: 0.0.0.0/0