helm:
  parameters:
  - name: cloudflare-tunnel.image.repository
    value: cloudflare/cloudflared
    forcestring: true
  - name: cloudflare-tunnel.image.tag
    value: latest@sha256:c18744ae1767c17c5562cc731c24e64a5a2f93f35c3dd6629b90dedaff6dff8f
    forcestring: true
