apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediadepot-downloads
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: ceph-filesystem-bronze