apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediadepot-downloads
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: ec-gold-r1
