helm:
  parameters:
  - name: tautulli.image.repository
    value: ghcr.io/linuxserver/tautulli
    forcestring: true
  - name: tautulli.image.tag
    value: latest@sha256:54d34b0695eb536c7fe648dd34e5f7bd9247a974166e758fdde9130630fe6c97
    forcestring: true
