helm:
  parameters:
  - name: tautulli.image.repository
    value: ghcr.io/linuxserver/tautulli
    forcestring: true
  - name: tautulli.image.tag
    value: latest@sha256:20fc05cad3c300f3cab16be60180f1d230ba8a33f10c66315e591ea8a5d5ea39
    forcestring: true
