helm:
  parameters:
  - name: tautulli.image.repository
    value: ghcr.io/linuxserver/tautulli
    forcestring: true
  - name: tautulli.image.tag
    value: latest@sha256:3480921343939f861a3b12583557b99f744d626c6f838681b06b032a25cdfff0
    forcestring: true
