helm:
  parameters:
  - name: tautulli.controllers.tautulli.containers.main.image.repository
    value: ghcr.io/linuxserver/tautulli
    forcestring: true
  - name: tautulli.controllers.tautulli.containers.main.image.tag
    value: 2.15.0
    forcestring: true
