helm:
  parameters:
  - name: tautulli.image.repository
    value: ghcr.io/linuxserver/tautulli
    forcestring: true
  - name: tautulli.image.tag
    value: latest@sha256:45ec9309450a6dd9bbf5760730642f2319d1f1e20aeb0bce6c8d0deafd2709fc
    forcestring: true
