---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-prod
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  acme:
    email: {{ .Values.letsEncrypt.email }}
    privateKeySecretRef:
      name:  acme-issuer-account-key
    server: {{ .Values.letsEncrypt.server }}
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token