{{- range $name, $value := .Values.sealedSecrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ $name }}
{{- with $value.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
spec:
  encryptedData:
    {{- range $fieldName, $fieldValue := $value.encryptedData }}
    {{ $fieldName }}: {{ $fieldValue }}
    {{- end }}
  template:
    metadata:
{{- with $value.labels }}
      labels:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with $value.annotations }}
      annotations:
{{- toYaml . | nindent 8 }}
{{- end }}
      creationTimestamp: null
      name: {{ $name }}
    type: {{ $value.type }}
{{- end }}