secrets-operator:
  controllerManager:
    manager:
      image:
        repository: infisical/kubernetes-operator
        tag: "v0.3.3"

sealedSecrets:
  service-token:
    encryptedData:
      infisicalToken: AgA0GMxhgv4zZrvyZDt3nG453RutNw0YQXkgeTWY9Oy5ptoHK9MGMB4lasSkySXzUHsZRj4IhjnIHFk+RTNSb0EJW5MF4/BPBQ46MzJjRQ9xwB1bR5rrfhhDI+IQLIUrRfw4iKBAlqsWUZbOOk0QpzTUEDjPTGkPaQ6BdTzgYOOeAU9k44nrb6yPDYYwej7ZQZ4wSfe03L98hV5Jno2Tu62OSsdCr47vX+ubqjB2sb8XKG2b62Mn7jmpY+6bPQG+goUMvH/PG7l64gZD738AjlKAo4AM9kNqT34rgNrLMf2ddunGU6+7fswGCR123pNW8fO7Gx9QzkI7G9DBHapni4Jr2nfXjIqCl8essps0fdaofIaleCUmWDzVUIYyb/ln6xFOKqiRHT2Ei0v8Zx0FhojxKtUPS1igcDzC6tjXq/vbBYPzIjL/Fmf4MaJcLuAOs1+ZZBqeKKuZas0AOdz45/I/bCRG0AIgYspcG5IipKBnXJvtjfPJ0HoaRBRs6Dgij1Lhl+aQQyceatyejAetY40JXdSVonBHcdgWfi4MMWJqht/o8US2Q2+v5AZTI5qgOt6C2h2nlffUG5HkV7cYLRqHo+tCa3taCdmYARd0NOwAVAG4kQ9WKGhsBTFyqAjFzCvBVZb5Et67B81+UQBHD+8LMrwR8Yx7WNI9/Sqg4SQICtVGyzD1FEpaF21BkVXCXwtDs1onbraK/pfa6Yiw2/rRwBH3fCnyxwwnPPqMd0osoPudJlT6VRCnE/tuNE5oL0p8IptA6GZipDVeMulreSy8d94F4vq5KVr1dMH7p0XZcNi+ADOVc4t7+Vak4E0=
    type: Opaque