babybuddy:
  global:
    fullnameOverride: babybuddy
  defaultPodOptions:
    automountServiceAccountToken: false
    dnsConfig:
      options:
        - name: ndots
          value: "2"
    labels:
      application: babybuddy
    securityContext:
      seccompProfile:
        type: RuntimeDefault
  controllers:
    babybuddy:
      type: deployment
      annotations:
        secrets.infisical.com/auto-reload: "true"
      containers:
        main:
          image:
            repository: ghcr.io/linuxserver/babybuddy
            tag: "2.2.1"
            pullPolicy: IfNotPresent
          env:
            TZ: "America/New_York"
            CSRF_TRUSTED_ORIGINS: "https://baby.xtr.pub"
          resources:
            limits:
              cpu: "2000m"
              memory: 384Mi
            requests:
              cpu: 75m
              memory: 128Mi
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
  service:
    app:
      controller: babybuddy
      ports:
        http:
          enabled: true
          primary: true
          port: 8000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
      hosts:
        - host: baby.xtr.pub
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: app
                port: http
      tls:
      - hosts:
        - baby.xtr.pub
        secretName: tls-secret
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 128Mi
      storageClass: ec-gold
      globalMounts:
        - path: /config

  networkpolicies:
    main:
      enabled: true
      controller: babybuddy
      policyTypes:
        - Ingress
        - Egress
      rules:
        ingress:
          - from:
              - namespaceSelector:
                  matchLabels:
                    name: traefik
                podSelector:
                  matchLabels:
                     app.kubernetes.io/name: traefik
        egress: []
