babybuddy:
  image:
    repository: registry.gitlab.com/linuxserver.io/docker-babybuddy/babybuddy
    tag: 1.11.1
  env:
    TZ: America/New_York

  probes:
    liveness:
      spec:
        periodSeconds: 2400

  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
      hosts:
      - host: baby.xtr.pub
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - baby.xtr.pub
        secretName: tls-secret

  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    config:
      enabled: true
      type: pvc
      accessMode: ReadWriteOnce
      size: 128Mi
      mountPath: /config
      storageClass: ceph-block-bronze
  resources:
    limits:
      cpu: 2000m
      memory: 384Mi
    requests:
      cpu: 125m
      memory: 128Mi

backupPlan:
  babybuddy:
    backupTarget: *target
    backupPlanFlags:
      skipImageBackup: true
    policies:
      retention-policy:
        type: Retention
        spec:
          cleanupConfig:
            backupDays: 2
          default: false
          retentionConfig:
            dayOfWeek: Sunday
            weekly: 1
            latest: 2
      fullbackup-policy:
        type: Schedule
        spec:
          default: false
          scheduleConfig:
            schedule:
            - 10 4 * 1/3 *
      incremental-policy:
        type: Schedule
        spec:
          default: false
          scheduleConfig:
            schedule:
            - 15 4 * * *
    excludeResources:
      gvkSelector:
      - groupVersionKind:
          group: secrets.infisical.com
          kind: InfisicalSecret
          version: v1alpha1
      labelSelector:
      - matchExpressions:
        - key: tvk-skip-object
          operator: In
          values:
          - "true"

infisicalSecret:
  *target:
    syncInterval: 900
    secretsPath: global