babybuddy:
  image:
    repository: registry.gitlab.com/linuxserver.io/docker-babybuddy/babybuddy
    tag: 1.11.1
  env:
    TZ: America/New_York

  probes:
    liveness:
      spec:
        periodSeconds: 2400

  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
      hosts:
      - host: baby.xtr.pub
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - baby.xtr.pub
        secretName: tls-secret

  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    config:
      enabled: true
      type: pvc
      accessMode: ReadWriteOnce
      size: 128Mi
      mountPath: /config
      storageClass: ceph-block-bronze
  resources:
    limits:
      cpu: 2000m
      memory: 384Mi
    requests:
      cpu: 125m
      memory: 128Mi
