k8s-triliovault-operator:
  deploy: true
  replicaCount: 1
  installTVK:
    enabled: false
  image:
    pullPolicy: IfNotPresent

tvkvaultmanager:
  enabled: true
  ingressConfig:
    host: "tvk.xtr.pub"
    annotations:
      cert-manager.io/cluster-issuer: le-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
  instanceName: conrad
  license:
    name: trilio-license
    key: xYENDgwKD3jajVHLboMwELz7Kyz1bNVgJ0AkDnkgtWqSViLkvjaLajUBZCBq/r6mHBpBFHVOK689M555SruS7sBS4VGfL6RYiJkbfEnWFqE1VbmBFukf4n7JuGDCI0lu+ht0hHgFjdEEdGsuSCfb1nZITkZj2eARbXPLEPtkB6ZssYRSY/JdG3sdDPS6EeNO2lmrzjWU1wnz/nlJGX2pzrgF5abEfqGlKzcNjvbdWaF9L7LGyd68Yx5J0V7Qvm7GlIWPUcilYKhmikl0BiDwgWmMIoU8CqWvSJrs6R3E7pzlRRBI6SHDQnPmeYhMzULBuNYygKjIZYhkO6Qxlo8Px2W2PQwc87n/kOM3LJj0cZvbR2f1JzT4oNJUVzXe+Yo+dU3rUuvXOXnrFGaTsP6Z1hpq0KYd1xd7c07XH1nzA7+CodQwLQIVAIrt9hMFwGKfa1jQP24VwQMbXNAxAhQgO8Jhcijtr0kvzfK+ZYcyLP/8Fw==X02g0
  componentConfiguration:
    admission-webhook:
      resources:
        requests:
          memory: "64Mi"
          cpu: "20m"
        limits:
          memory: "512Mi"
          cpu: "200m"
    control-plane:
      resources:
        requests:
          memory: "80Mi"
          cpu: "10m"
        limits:
          memory: "512Mi"
          cpu: "200m"
    exporter:
      resources:
        requests:
          memory: "75Mi"
          cpu: "25m"
        limits:
          memory: "512Mi"
          cpu: "250m"
    web:
      resources:
        requests:
          memory: "24Mi"
          cpu: "5m"
        limits:
          memory: "512Mi"
          cpu: "250m"
    web-backend:
      resources:
        requests:
          memory: "850Mi"
          cpu: "285m"
        limits:
          memory: "1500Mi"
          cpu: "500m"

# backupTargets:
#   backblaze-palebluedot:
#     nfsCredentials:
#       nfsExport: ""
#     objectStoreCredentials:
#       bucketName: palebluedot-tvk
#       credentialSecret:
#         apiVersion: v1
#         kind: Secret
#         name: backblaze-palebluedot
#       url: https://s3.us-west-000.backblazeb2.com 
#     thresholdCapacity: 100Gi
#     type: ObjectStore
#     vendor: Other

# clusterbackupplans:
#   default:
#     backupTarget: backblaze-palebluedot
#     clusterBackupPlanFlags:
#       skipImageBackup: true
#     namespaceSelector:
#     - labelSelector:
#       - matchLabels:
#           tvk-backup: default
#     policies:
#       retention-policy:
#         type: Retention
#         spec:
#           cleanupConfig:
#             backupDays: 7
#           default: false
#           retentionConfig:
#             dayOfWeek: Sunday
#             latest: 15
#             weekly: 2
#       incremental-policy:
#         type: Schedule
#         spec:
#           default: false
#           scheduleConfig:
#             schedule:
#             - 5 4 * * *
#       fullbackup-policy:
#         type: Schedule
#         spec:
#           default: false
#           scheduleConfig:
#             schedule:
#             - 0 4 * 1/3 *
#     excludeResources:
#       labelSelector:
#       - matchExpressions:
#         - key: tvk-skip-object
#           operator: In
#           values:
#           - "true"
#   low-priority:
#     backupTarget: backblaze-palebluedot
#     clusterBackupPlanFlags:
#       skipImageBackup: true
#     namespaceSelector:
#     - labelSelector:
#       - matchLabels:
#           tvk-backup: low-pri
#     policies:
#       retention-policy:
#         type: Retention
#         spec:
#           cleanupConfig:
#             backupDays: 7
#           default: false
#           retentionConfig:
#             dayOfWeek: Sunday
#             latest: 15
#       incremental-policy:
#         type: Schedule
#         spec:
#           default: false
#           scheduleConfig:
#             schedule:
#             - 15 4 * * *
#       fullbackup-policy:
#         type: Schedule
#         spec:
#           default: false
#           scheduleConfig:
#             schedule:
#             - 10 4 * 1/3 *
#     excludeResources:
#       labelSelector:
#       - matchExpressions:
#         - key: tvk-skip-object
#           operator: In
#           values:
#           - "true"