{{ range $name, $pool := $.Values.lbIP }}
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: {{ $name }}
spec:
  cidrs:
  - cidr: {{ .cidr | quote }}
  {{ with .selector }}
  {{ toYaml . | nindent 2 }}
  {{ end }}
{{- if .l2announcements }}
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: {{ $name }}-policy
spec:
  {{ with .selector }}
  {{ toYaml . | nindent 2 }}
  {{ end }}
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  interfaces:
  {{ range $int := .l2announcements.interfaces }}
    - {{ .  }}
  {{ end }}
  loadBalancerIPs: true
{{- end }}

{{- end }}