{{ if .Values.infraBackup.backupVol.pvcName  }}
{{ with .Values.infraBackup.backupVol }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .pvcName }}
spec:
  accessModes:
    - {{ required (printf "accessMode is required for PVC %v" .pvcName) .accessMode | quote }}
  resources:
    requests:
      storage: {{ required (printf "size is required for PVC %v" .pvcName) .size | quote }}
  {{- if .storageClass }}
  storageClassName: {{ if (eq "-" .storageClass) }}""{{- else }}{{ .storageClass | quote }}{{- end }}
  {{- end }}
  {{- if .volumeName }}
  volumeName: {{ .volumeName | quote }}
  {{- end }}
{{ end }}
{{ end }}