{{- if (.Values.infraBackup | default dict).enabled }}
{{- with .Values.infraBackup }}
{{- if ( .backupPruning | default dict).enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-backups
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: infra-backups-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infra-backups-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infra-backups-role
subjects:
  - kind: ServiceAccount
    name: infra-backups
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}