cert-manager:
  global:
    logLevel: 4
    leaderElection:
      namespace: "kube-system"
      leaseDuration: 60s
      renewDeadline: 40s
      retryPeriod: 15s
  installCRDs: true
  # crds:
  #   enabled: true
  #   keep: false
  maxConcurrentChallenges: 15
  enableCertificateOwnerRef: true
  podLabels:
    application: cert-manager
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - ike
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - operator: Exists
    key: CriticalAddonsOnly
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 250m
      memory: 192Mi
  webhook:
    podLabels:
      application: cert-manager
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 10
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: application
                operator: In
                values:
                - cert-manager
            topologyKey: kubernetes.io/hostname
    resources:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        cpu: 250m
        memory: 96Mi
  cainjector:
    podLabels:
      application: cert-manager
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 10
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: application
                operator: In
                values:
                - cert-manager
            topologyKey: kubernetes.io/hostname
    resources:
      requests:
        cpu: 125m
        memory: 128Mi
      limits:
        cpu: 400m
        memory: 512Mi
  startupapicheck:
    podLabels:
      application: cert-manager
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 10
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: application
                operator: In
                values:
                - cert-manager
            topologyKey: kubernetes.io/hostname
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 75m
        memory: 96Mi
  # podDnsPolicy: "None"
  # podDnsConfig:
  #   nameservers:
  #     - "1.0.0.1"
  #     - "1.1.1.1"

letsEncrypt:
  email: erkerb@gmail.com
#  server: https://acme-staging-v02.api.letsencrypt.org/directory
  server: https://acme-v02.api.letsencrypt.org/directory

infisicalSecret:
  cloudflare-api-token:
    syncInterval: 86400