helm:
  parameters:
  - name: overseerr.controllers.overseer.containers.main.image.repository
    value: ghcr.io/linuxserver/overseerr
    forcestring: true
  - name: overseerr.controllers.overseer.containers.main.image.tag
    value: latest@sha256:6baa11c3461fcc3edea229b6934c0621cc8f7976b94676ccea4c18599a30b57b
    forcestring: true
