apiVersion: v2
description: Overseerr is a free and open source software application for managing requests for your media library. It integrates with your existing services such as Sonarr, Radarr and Plex!
name: overseerr
version: 5.2.0
kubeVersion: ">=1.16.0-0"
keywords:
- overseerr
- plex
- sonarr
- radarr
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/overseerr
icon: https://i.imgur.com/TMoEG7g.png
sources:
- https://github.com/sct/overseerr
- https://hub.docker.com/r/sctx/overseerr
dependencies:
- name: overseerr
  repository: "@k8s-at-home"
  version: "5.2.0"