reloader:
  reloader:
    readOnlyRootFileSystem: true
    deployment:
      resources:
        limits:
          cpu: 100m
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 128Mi
      livenessProbe:
        timeoutSeconds: 5
        failureThreshold: 10
        periodSeconds: 10
        successThreshold: 1
      readinessProbe:
        timeoutSeconds: 15
        failureThreshold: 5
        periodSeconds: 10
        successThreshold: 1
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        capabilities:
          drop:
            - ALL
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
    serviceMonitor:
      enabled: false
    podMonitor:
      enabled: false