apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: internal-apps-deployments
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@github.com:erkerb4/home-k8s-gitops.git
      revision: HEAD
      directories:
      - path: apps/internal-apps/*
  template:
    metadata:
      name: '{{path.basename}}'
      annotations:
        notifications.argoproj.io/subscribe.app-outofsync.slack: argo
        notifications.argoproj.io/subscribe.on-health-degraded.slack: argo
        notifications.argoproj.io/subscribe.on-sync-failed.slack: argo
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argo

        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/git-branch: main:image-updater-{{.SHA256}}
        argocd-image-updater.argoproj.io/image-list: actual=ghcr.io/actualbudget/actual-server:24.x,babybuddy=registry.gitlab.com/linuxserver.io/docker-babybuddy/babybuddy:2.x,meilisearch=getmeili/meilisearch:v1.x, barlie-redis=redis:7.x,barlie-assistant=barassistant/server:3.x,barlie-sr=barassistant/salt-rim:2.x,changed=ghcr.io/dgtlmoon/changedetection.io:0.x,mealie=ghcr.io/mealie-recipes/mealie:v1.x,sabnzbd=quay.io/linuxserver.io/sabnzbd:4.2.x,radarr=quay.io/linuxserver.io/radarr:5.3.x,omada=mbentley/omada-controller:5.13,receipt-fe=noah231515/receipt-wrangler-desktop:latest,receipt-api=noah231515/receipt-wrangler-api:latest,receipt-db=mariadb:10.11.x,tautulli=ghcr.io/linuxserver/tautulli:2.13.x

        argocd-image-updater.argoproj.io/actual.helm.image-name: actual.controllers.main.containers.main.image.repository
        argocd-image-updater.argoproj.io/actual.helm.image-tag: actual.controllers.main.containers.main.image.tag

        argocd-image-updater.argoproj.io/babybuddy.helm.image-name: babybuddy.controllers.babybuddy.containers.main.image.repository
        argocd-image-updater.argoproj.io/babybuddy.helm.image-tag: babybuddy.controllers.babybuddy.containers.main.image.tag

        argocd-image-updater.argoproj.io/meilisearch.helm.image-name: barlie.controllers.meilisearch.containers.main.image.repository
        argocd-image-updater.argoproj.io/meilisearch.helm.image-tag: barlie.controllers.meilisearch.containers.main.image.tag
        argocd-image-updater.argoproj.io/barlie-redis.helm.image-name: barlie.controllers.redis.containers.main.image.repository
        argocd-image-updater.argoproj.io/barlie-redis.helm.image-tag: barlie.controllers.redis.containers.main.image.tag
        argocd-image-updater.argoproj.io/barlie-assistant.helm.image-name: barlie.controllers.assistant.containers.main.image.repository
        argocd-image-updater.argoproj.io/barlie-assistant.helm.image-tag: barlie.controllers.assistant.containers.main.image.tag
        argocd-image-updater.argoproj.io/barlie-sr.helm.image-name: barlie.controllers.salt-rim.containers.main.image.repository
        argocd-image-updater.argoproj.io/barlie-sr.helm.image-tag: barlie.controllers.salt-rim.containers.main.image.tag

        argocd-image-updater.argoproj.io/changed.helm.image-name: changedetection.controllers.changedetection.containers.main.image.repository
        argocd-image-updater.argoproj.io/changed.helm.image-tag: changedetection.controllers.changedetection.containers.main.image.tag

        argocd-image-updater.argoproj.io/mealie.helm.image-name: mealie.controllers.mealie.containers.main.image.repository
        argocd-image-updater.argoproj.io/mealie.helm.image-tag: mealie.controllers.mealie.containers.main.image.tag

        argocd-image-updater.argoproj.io/sabnzbd.helm.image-name: sabnzbd.controllers.sabnzbd.containers.main.image.repository
        argocd-image-updater.argoproj.io/sabnzbd.helm.image-tag: sabnzbd.controllers.sabnzbd.containers.main.image.tag

        # sonarr=quay.io/linuxserver.io/sonarr:4.0.0
        # argocd-image-updater.argoproj.io/sonarr.helm.image-name: sonarr.image.repository
        # argocd-image-updater.argoproj.io/sonarr.helm.image-tag: sonarr.image.tag
        # argocd-image-updater.argoproj.io/sonarr.update-strategy: digest

        argocd-image-updater.argoproj.io/radarr.helm.image-name: radarr.controllers.main.containers.main.image.repository
        argocd-image-updater.argoproj.io/radarr.helm.image-tag: radarr.controllers.main.containers.main.image.tag

        argocd-image-updater.argoproj.io/omada.helm.image-name: omada.controllers.omada.containers.main.image.repository
        argocd-image-updater.argoproj.io/omada.helm.image-tag: omada.controllers.omada.containers.main.image.repository
        argocd-image-updater.argoproj.io/omada.update-strategy: digest

        argocd-image-updater.argoproj.io/receipt-fe.helm.image-name: receipt.controllers.frontend.containers.main.image.repository
        argocd-image-updater.argoproj.io/receipt-fe.helm.image-tag: receipt.controllers.frontend.containers.main.image.repository
        argocd-image-updater.argoproj.io/receipt-fe.update-strategy: digest
        argocd-image-updater.argoproj.io/receipt-api.helm.image-name: receipt.controllers.api.containers.main.image.repository
        argocd-image-updater.argoproj.io/receipt-api.helm.image-tag: receipt.controllers.api.containers.main.image.repository
        argocd-image-updater.argoproj.io/receipt-api.update-strategy: digest
        argocd-image-updater.argoproj.io/receipt-db.helm.image-name: receipt.controllers.db.containers.main.image.repository
        argocd-image-updater.argoproj.io/receipt-db.helm.image-tag: receipt.controllers.db.containers.main.image.repository

        argocd-image-updater.argoproj.io/tautulli.helm.image-name: tautulli.controllers.main.containers.main.image.repository
        argocd-image-updater.argoproj.io/tautulli.helm.image-tag: tautulli.controllers.main.containers.main.image.tag
        argocd-image-updater.argoproj.io/tautulli.ignore-tags: version-v*,v*

      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: internal-apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - PruneLast=true
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
      source:
        repoURL: git@github.com:erkerb4/home-k8s-gitops.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'