apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: internal-apps-deployments
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@github.com:erkerb4/home-k8s-gitops.git
      revision: HEAD
      directories:
      - path: apps/internal-apps/*
  template:
    metadata:
      name: '{{path.basename}}'
      annotations:
        notifications.argoproj.io/subscribe.app-outofsync.slack: argo
        notifications.argoproj.io/subscribe.on-health-degraded.slack: argo
        notifications.argoproj.io/subscribe.on-sync-failed.slack: argo
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argo
              
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/git-branch: main:image-updater-{{.SHA256}}
        argocd-image-updater.argoproj.io/image-list: sabnzbd=quay.io/linuxserver.io/sabnzbd:4.x,sonarr=quay.io/linuxserver.io/sonarr:4.0.x,radarr=quay.io/linuxserver.io/radarr:5.x,changed=ghcr.io/dgtlmoon/changedetection.io:0.x,tautulli=ghcr.io/linuxserver/tautulli:latest,babybuddy=registry.gitlab.com/linuxserver.io/docker-babybuddy/babybuddy:1.x,omada=mbentley/omada-controller:5.13.x

        argocd-image-updater.argoproj.io/sabnzbd.helm.image-name: sabnzbd.image.repository
        argocd-image-updater.argoproj.io/sabnzbd.helm.image-tag: sabnzbd.image.tag

        argocd-image-updater.argoproj.io/sonarr.helm.image-name: sonarr.image.repository
        argocd-image-updater.argoproj.io/sonarr.helm.image-tag: sonarr.image.tag

        argocd-image-updater.argoproj.io/radarr.helm.image-name: radarr.image.repository
        argocd-image-updater.argoproj.io/radarr.helm.image-tag: radarr.image.tag

        argocd-image-updater.argoproj.io/babybuddy.helm.image-name: babybuddy.image.repository
        argocd-image-updater.argoproj.io/babybuddy.helm.image-tag: babybuddy.image.tag

        argocd-image-updater.argoproj.io/changed.helm.image-name: changedetection-io.image.repository
        argocd-image-updater.argoproj.io/changed.helm.image-tag: changedetection-io.image.tag

        argocd-image-updater.argoproj.io/tautulli.helm.image-name: tautulli.image.repository
        argocd-image-updater.argoproj.io/tautulli.helm.image-tag: tautulli.image.tag
        argocd-image-updater.argoproj.io/tautulli.ignore-tags: unstable, develop
        argocd-image-updater.argoproj.io/tautulli.update-strategy: digest

        argocd-image-updater.argoproj.io/omada.helm.image-name: omada.controllers.main.containers.main.image
        argocd-image-updater.argoproj.io/omada.helm.image-tag: omada.controllers.main.containers.main.tag
        
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: internal-apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - PruneLast=true
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
      source:
        repoURL: git@github.com:erkerb4/home-k8s-gitops.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'