apiVersion: v2
name: cilium
version: 1.15.4
description: eBPF-based Networking, Security, and Observability
keywords:
  - BPF
  - eBPF
  - Kubernetes
  - Networking
  - Security
  - Observability
  - Troubleshooting
sources:
  - https://github.com/cilium/cilium
dependencies:
  - name: cilium
    version: "1.15.3"
    repository: '@cilium'