cilium:
  extraEnv:
    - name: TZ
      value: "America/New_York"
  endpointRoutes:
    enabled: true
  hubble:
    relay:
      enabled: true
      rollOutPods: true
    tls:
      enabled: false
    ui:
      enabled: true
      rollOutPods: true
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: le-prod
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
        hosts:
          - hobble.xtr.pub
        tls:
        - hosts:
          - hobble.xtr.pub
          secretName: tls-secret
  ipam:
    mode: cluster-pool
    operator:
      clusterPoolIPv4MaskSize: 24
      clusterPoolIPv4PodCIDRList: ["172.30.0.0/20"]
  k8sServiceHost: 192.168.30.10
  k8sServicePort: 6443
  kubeProxyReplacement: true
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1500m
      memory: 1250Mi
  socketLB:
    enabled: true
    hostNamespaceOnly: true
  externalIPs:
    enabled: false
  nodePort:
    enabled: true
  hostPort:
    enabled: true
  l2announcements:
    enabled: true
    leaseDuration: 15s
    leaseRenewDeadline: 5s
    leaseRetryPeriod: 2s
  # routingMode: "native"
  # ipv4NativeRoutingCIDR: "172.30.0.0/20"
  autoDirectNodeRoutes: true
  annotateK8sNode: true
  bpf:
    masquerade: true
  ipMasqAgent:
    enabled: true
    config:
      nonMasqueradeCIDRs:
       - 172.30.0.0/16
  enableIPv4BIGTCP: true
  installNoConntrackIptablesRules: true
  loadBalancer:
    acceleration: best-effort
    mode: hybrid

lbIP:
  xtr-pool:
    cidr: 192.168.30.1/26
    selector:
      serviceSelector:
        matchLabels:
          lb: "true"
    l2announcements:
      interfaces: ["enp2s0f1", "enp1s0"]